apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rollouts.hringhorni.nu.dev
spec:
  group: hringhorni.nu.dev
  names:
    kind: Rollout
    listKind: RolloutList
    plural: rollouts
    shortNames:
    - ro
    singular: rollout
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    schema:
      openAPIV3Schema:
        type: object
        # One can use x-kubernetes-preserve-unknown-fields: true
        # at the root of the schema (and inside any properties, additionalProperties)
        # to get the traditional CRD behaviour that nothing is pruned, despite
        # setting spec.preserveUnknownProperties: false.
        #
        # See https://kubernetes.io/blog/2019/06/20/crd-structural-schema/
        # See issue: https://github.com/knative/serving/issues/912
        x-kubernetes-preserve-unknown-fields: true
    additionalPrinterColumns:
    - name: App
      type: string
      jsonPath: ".spec.appName"
    - name: Revision
      type: string
      jsonPath: ".spec.revision"
    - name: Succeeded
      type: string
      jsonPath: .status.conditions[?(@.type == "RolloutSucceeded")].status
    - name: Reason
      type: string
      jsonPath: .status.conditions[?(@.type == "RolloutSucceeded")].reason
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
