apiVersion: v1
kind: Service
metadata:
  name: greeting-api
  namespace: default
  labels:
    app: greeting-api
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30000
    - name: metrics
      port: 2112
  selector:
    app: greeting-api
