apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: greeting-api
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 60s
      scrapeTimeout: 45s
  selector:
    matchLabels:
      app: greeting-api
