apiVersion: hringhorni.nu.dev/v1alpha1
kind: Rollout
metadata:
  name: greeting-api-ghi
  namespace: default
spec:
  appName: greeting-api
  revision: e2079325dff82a0274b7d774b0dd09ae8d676d18
  replicas: 4
  timeout: 1m
  selector:
    matchLabels:
      app: greeting-api
  template:
    metadata:
      labels:
        app: greeting-api
    spec:
      containers:
      - name: greeting-api
        image: ko://github.com/nubank/hringhorni/e2e/cmd/stable
        ports:
          - name: http
            containerPort: 8080
          - name: metrics
            containerPort: 2112

        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          capabilities:
            drop:
            - all
