apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: hringhorni
  app.kubernetes.io/part-of: hringhorni
resources:
  - config-defaults.yaml
  - config-leader-election.yaml
  - config-logging.yaml
  - config-observability.yaml
