// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccountCredentials AccountCredentials
//
// swagger:model AccountCredentials
type AccountCredentials struct {

	// locations
	Locations []string `json:"locations"`

	// name
	Name string `json:"name,omitempty"`

	// recommended locations
	RecommendedLocations []string `json:"recommendedLocations"`

	// supported types
	SupportedTypes []string `json:"supportedTypes"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this account credentials
func (m *AccountCredentials) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSupportedTypes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var accountCredentialsSupportedTypesItemsEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["METRICS_STORE","OBJECT_STORE","CONFIGURATION_STORE","REMOTE_JUDGE"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		accountCredentialsSupportedTypesItemsEnum = append(accountCredentialsSupportedTypesItemsEnum, v)
	}
}

func (m *AccountCredentials) validateSupportedTypesItemsEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, accountCredentialsSupportedTypesItemsEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *AccountCredentials) validateSupportedTypes(formats strfmt.Registry) error {
	if swag.IsZero(m.SupportedTypes) { // not required
		return nil
	}

	for i := 0; i < len(m.SupportedTypes); i++ {

		// value enum
		if err := m.validateSupportedTypesItemsEnum("supportedTypes"+"."+strconv.Itoa(i), "body", m.SupportedTypes[i]); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this account credentials based on context it is used
func (m *AccountCredentials) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountCredentials) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountCredentials) UnmarshalBinary(b []byte) error {
	var res AccountCredentials
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
