// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ActionContext ActionContext
//
// swagger:model ActionContext
type ActionContext struct {

	// stage Id
	StageID string `json:"stageId,omitempty"`

	// stage start time
	StageStartTime int64 `json:"stageStartTime,omitempty"`

	// stage type
	StageType string `json:"stageType,omitempty"`

	// task Id
	TaskID string `json:"taskId,omitempty"`

	// task start time
	TaskStartTime int64 `json:"taskStartTime,omitempty"`

	// task type
	TaskType string `json:"taskType,omitempty"`
}

// Validate validates this action context
func (m *ActionContext) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this action context based on context it is used
func (m *ActionContext) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ActionContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ActionContext) UnmarshalBinary(b []byte) error {
	var res ActionContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
