// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuthenticationDetails AuthenticationDetails
//
// swagger:model AuthenticationDetails
type AuthenticationDetails struct {

	// allowed accounts
	AllowedAccounts []string `json:"allowedAccounts"`

	// user
	User string `json:"user,omitempty"`
}

// Validate validates this authentication details
func (m *AuthenticationDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this authentication details based on context it is used
func (m *AuthenticationDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuthenticationDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuthenticationDetails) UnmarshalBinary(b []byte) error {
	var res AuthenticationDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
