// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CanaryScopePair CanaryScopePair
//
// swagger:model CanaryScopePair
type CanaryScopePair struct {

	// control scope
	ControlScope *CanaryScope `json:"controlScope,omitempty"`

	// experiment scope
	ExperimentScope *CanaryScope `json:"experimentScope,omitempty"`
}

// Validate validates this canary scope pair
func (m *CanaryScopePair) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateControlScope(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExperimentScope(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CanaryScopePair) validateControlScope(formats strfmt.Registry) error {
	if swag.IsZero(m.ControlScope) { // not required
		return nil
	}

	if m.ControlScope != nil {
		if err := m.ControlScope.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("controlScope")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("controlScope")
			}
			return err
		}
	}

	return nil
}

func (m *CanaryScopePair) validateExperimentScope(formats strfmt.Registry) error {
	if swag.IsZero(m.ExperimentScope) { // not required
		return nil
	}

	if m.ExperimentScope != nil {
		if err := m.ExperimentScope.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("experimentScope")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("experimentScope")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this canary scope pair based on the context it is used
func (m *CanaryScopePair) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateControlScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExperimentScope(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CanaryScopePair) contextValidateControlScope(ctx context.Context, formats strfmt.Registry) error {

	if m.ControlScope != nil {
		if err := m.ControlScope.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("controlScope")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("controlScope")
			}
			return err
		}
	}

	return nil
}

func (m *CanaryScopePair) contextValidateExperimentScope(ctx context.Context, formats strfmt.Registry) error {

	if m.ExperimentScope != nil {
		if err := m.ExperimentScope.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("experimentScope")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("experimentScope")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CanaryScopePair) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryScopePair) UnmarshalBinary(b []byte) error {
	var res CanaryScopePair
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
