// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CanaryAnalysisExecutionResponse CanaryAnalysisExecutionResponse
//
// Wrapper object around the canary analysis execution id.
//
// swagger:model CanaryAnalysisExecutionResponse
type CanaryAnalysisExecutionResponse struct {

	// The id of the execution
	// Example: 01CYZCD53RBX2KR2Q9GY0218TV
	CanaryAnalysisExecutionID string `json:"canaryAnalysisExecutionId,omitempty"`
}

// Validate validates this canary analysis execution response
func (m *CanaryAnalysisExecutionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this canary analysis execution response based on context it is used
func (m *CanaryAnalysisExecutionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CanaryAnalysisExecutionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryAnalysisExecutionResponse) UnmarshalBinary(b []byte) error {
	var res CanaryAnalysisExecutionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
