// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CanaryClassifierConfig CanaryClassifierConfig
//
// The classification configuration, such as group weights.
//
// swagger:model CanaryClassifierConfig
type CanaryClassifierConfig struct {

	// List of each metrics group along with its corresponding weight. Weights must total 100.
	// Example: {"app-group":30,"pod-group":70}
	GroupWeights map[string]float64 `json:"groupWeights,omitempty"`
}

// Validate validates this canary classifier config
func (m *CanaryClassifierConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this canary classifier config based on context it is used
func (m *CanaryClassifierConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CanaryClassifierConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryClassifierConfig) UnmarshalBinary(b []byte) error {
	var res CanaryClassifierConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
