// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CanaryJudge CanaryJudge
//
// swagger:model CanaryJudge
type CanaryJudge struct {

	// name
	Name string `json:"name,omitempty"`

	// visible
	Visible bool `json:"visible,omitempty"`
}

// Validate validates this canary judge
func (m *CanaryJudge) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this canary judge based on context it is used
func (m *CanaryJudge) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CanaryJudge) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryJudge) UnmarshalBinary(b []byte) error {
	var res CanaryJudge
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
