// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CanaryJudgeScore CanaryJudgeScore
//
// swagger:model CanaryJudgeScore
type CanaryJudgeScore struct {

	// classification
	Classification string `json:"classification,omitempty"`

	// classification reason
	ClassificationReason string `json:"classificationReason,omitempty"`

	// score
	Score float64 `json:"score,omitempty"`
}

// Validate validates this canary judge score
func (m *CanaryJudgeScore) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this canary judge score based on context it is used
func (m *CanaryJudgeScore) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CanaryJudgeScore) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryJudgeScore) UnmarshalBinary(b []byte) error {
	var res CanaryJudgeScore
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
