// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CanaryJudgeConfig CanaryJudgeConfig
//
// Judge configuration.
//
// swagger:model CanaryJudgeConfig
type CanaryJudgeConfig struct {

	// Additional judgement configuration. As of right now, this should always be an empty object.
	// Example: {}
	// Required: true
	JudgeConfigurations interface{} `json:"judgeConfigurations"`

	// Judge to use, as of right now there is only `NetflixACAJudge-v1.0`.
	// Example: NetflixACAJudge-v1.0
	// Required: true
	Name *string `json:"name"`
}

// Validate validates this canary judge config
func (m *CanaryJudgeConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateJudgeConfigurations(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CanaryJudgeConfig) validateJudgeConfigurations(formats strfmt.Registry) error {

	if m.JudgeConfigurations == nil {
		return errors.Required("judgeConfigurations", "body", nil)
	}

	return nil
}

func (m *CanaryJudgeConfig) validateName(formats strfmt.Registry) error {

	if err := validate.Required("name", "body", m.Name); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this canary judge config based on context it is used
func (m *CanaryJudgeConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CanaryJudgeConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryJudgeConfig) UnmarshalBinary(b []byte) error {
	var res CanaryJudgeConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
