// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CanaryExecutionResponse CanaryExecutionResponse
//
// swagger:model CanaryExecutionResponse
type CanaryExecutionResponse struct {

	// canary execution Id
	CanaryExecutionID string `json:"canaryExecutionId,omitempty"`
}

// Validate validates this canary execution response
func (m *CanaryExecutionResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this canary execution response based on context it is used
func (m *CanaryExecutionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CanaryExecutionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryExecutionResponse) UnmarshalBinary(b []byte) error {
	var res CanaryExecutionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
