// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CanaryAdhocExecutionRequest CanaryAdhocExecutionRequest
//
// swagger:model CanaryAdhocExecutionRequest
type CanaryAdhocExecutionRequest struct {

	// canary config
	CanaryConfig *CanaryConfig `json:"canaryConfig,omitempty"`

	// execution request
	ExecutionRequest *CanaryExecutionRequest `json:"executionRequest,omitempty"`
}

// Validate validates this canary adhoc execution request
func (m *CanaryAdhocExecutionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCanaryConfig(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutionRequest(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CanaryAdhocExecutionRequest) validateCanaryConfig(formats strfmt.Registry) error {
	if swag.IsZero(m.CanaryConfig) { // not required
		return nil
	}

	if m.CanaryConfig != nil {
		if err := m.CanaryConfig.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("canaryConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("canaryConfig")
			}
			return err
		}
	}

	return nil
}

func (m *CanaryAdhocExecutionRequest) validateExecutionRequest(formats strfmt.Registry) error {
	if swag.IsZero(m.ExecutionRequest) { // not required
		return nil
	}

	if m.ExecutionRequest != nil {
		if err := m.ExecutionRequest.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("executionRequest")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("executionRequest")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this canary adhoc execution request based on the context it is used
func (m *CanaryAdhocExecutionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCanaryConfig(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateExecutionRequest(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CanaryAdhocExecutionRequest) contextValidateCanaryConfig(ctx context.Context, formats strfmt.Registry) error {

	if m.CanaryConfig != nil {
		if err := m.CanaryConfig.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("canaryConfig")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("canaryConfig")
			}
			return err
		}
	}

	return nil
}

func (m *CanaryAdhocExecutionRequest) contextValidateExecutionRequest(ctx context.Context, formats strfmt.Registry) error {

	if m.ExecutionRequest != nil {
		if err := m.ExecutionRequest.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("executionRequest")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("executionRequest")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CanaryAdhocExecutionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryAdhocExecutionRequest) UnmarshalBinary(b []byte) error {
	var res CanaryAdhocExecutionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
