// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CanaryClassifierThresholdsConfig CanaryClassifierThresholdsConfig
//
// Sets thresholds for canary score.
//
// swagger:model CanaryClassifierThresholdsConfig
type CanaryClassifierThresholdsConfig struct {

	// If canary score is lower than this value -- canary is considered marginal (failed).
	// Example: 50
	Marginal float64 `json:"marginal,omitempty"`

	// If canary score is higher than this value -- canary is considered successful.
	// Example: 75
	Pass float64 `json:"pass,omitempty"`
}

// Validate validates this canary classifier thresholds config
func (m *CanaryClassifierThresholdsConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this canary classifier thresholds config based on context it is used
func (m *CanaryClassifierThresholdsConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CanaryClassifierThresholdsConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CanaryClassifierThresholdsConfig) UnmarshalBinary(b []byte) error {
	var res CanaryClassifierThresholdsConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
