// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// MapStringObject Map«string,object»
//
// swagger:model Map«string,object»
type MapStringObject map[string]interface{}

// Validate validates this map string object
func (m MapStringObject) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this map string object based on context it is used
func (m MapStringObject) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
