// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MetricSetPair MetricSetPair
//
// swagger:model MetricSetPair
type MetricSetPair struct {

	// attributes
	Attributes map[string]map[string]string `json:"attributes,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// scopes
	Scopes map[string]MetricSetScope `json:"scopes,omitempty"`

	// tags
	Tags map[string]string `json:"tags,omitempty"`

	// values
	Values map[string][]float64 `json:"values,omitempty"`
}

// Validate validates this metric set pair
func (m *MetricSetPair) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateScopes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricSetPair) validateScopes(formats strfmt.Registry) error {
	if swag.IsZero(m.Scopes) { // not required
		return nil
	}

	for k := range m.Scopes {

		if err := validate.Required("scopes"+"."+k, "body", m.Scopes[k]); err != nil {
			return err
		}
		if val, ok := m.Scopes[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("scopes" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("scopes" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this metric set pair based on the context it is used
func (m *MetricSetPair) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateScopes(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MetricSetPair) contextValidateScopes(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Scopes {

		if val, ok := m.Scopes[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MetricSetPair) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricSetPair) UnmarshalBinary(b []byte) error {
	var res MetricSetPair
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
