// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// MetricSetScope MetricSetScope
//
// swagger:model MetricSetScope
type MetricSetScope struct {

	// start time iso
	StartTimeIso string `json:"startTimeIso,omitempty"`

	// start time millis
	StartTimeMillis int64 `json:"startTimeMillis,omitempty"`

	// step millis
	StepMillis int64 `json:"stepMillis,omitempty"`
}

// Validate validates this metric set scope
func (m *MetricSetScope) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this metric set scope based on context it is used
func (m *MetricSetScope) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MetricSetScope) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetricSetScope) UnmarshalBinary(b []byte) error {
	var res MetricSetScope
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
