// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PausedDetails PausedDetails
//
// swagger:model PausedDetails
type PausedDetails struct {

	// pause time
	PauseTime int64 `json:"pauseTime,omitempty"`

	// paused
	Paused bool `json:"paused,omitempty"`

	// paused by
	PausedBy string `json:"pausedBy,omitempty"`

	// paused ms
	PausedMs int64 `json:"pausedMs,omitempty"`

	// resume time
	ResumeTime int64 `json:"resumeTime,omitempty"`

	// resumed by
	ResumedBy string `json:"resumedBy,omitempty"`
}

// Validate validates this paused details
func (m *PausedDetails) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this paused details based on context it is used
func (m *PausedDetails) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PausedDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PausedDetails) UnmarshalBinary(b []byte) error {
	var res PausedDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
