apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: hringhorni
  app.kubernetes.io/part-of: hringhorni
resources:
  - service-account.yaml
  - rbac.yaml
  - deployment.yaml
